# Generated by Django 2.2.1 on 2020-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_time',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='労働時間'),
        ),
    ]
