# Generated by Django 2.2.1 on 2020-10-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0003_auto_20201001_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='work_time',
        ),
    ]
