# Generated by Django 2.2.1 on 2020-10-01 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0006_auto_20201001_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='労働時間'),
        ),
    ]
