# Generated by Django 2.2.1 on 2020-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0007_auto_20201001_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence',
            field=models.BooleanField(default=False, verbose_name='欠勤'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early',
            field=models.BooleanField(default=False, verbose_name='早退'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late',
            field=models.BooleanField(default=False, verbose_name='遅刻'),
        ),
    ]
