# Generated by Django 2.2.1 on 2020-10-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0008_auto_20201003_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='early',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late',
        ),
    ]
